# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 738)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plaintext_input_prompt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext_input_prompt.setGeometry(QtCore.QRect(10, 10, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plaintext_input_prompt.setFont(font)
        self.plaintext_input_prompt.setStyleSheet("")
        self.plaintext_input_prompt.setPlainText("")
        self.plaintext_input_prompt.setObjectName("plaintext_input_prompt")
        self.button_process_text_prompt = QtWidgets.QPushButton(self.centralwidget)
        self.button_process_text_prompt.setGeometry(QtCore.QRect(10, 160, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_process_text_prompt.setFont(font)
        self.button_process_text_prompt.setStyleSheet("")
        self.button_process_text_prompt.setObjectName("button_process_text_prompt")
        self.button_clear_chat = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear_chat.setGeometry(QtCore.QRect(10, 210, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_clear_chat.setFont(font)
        self.button_clear_chat.setStyleSheet("")
        self.button_clear_chat.setObjectName("button_clear_chat")
        self.combo_model_list = QtWidgets.QComboBox(self.centralwidget)
        self.combo_model_list.setGeometry(QtCore.QRect(10, 110, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_model_list.setFont(font)
        self.combo_model_list.setStyleSheet("")
        self.combo_model_list.setObjectName("combo_model_list")
        self.plaintext_output_prompt = QtWidgets.QTextEdit(self.centralwidget)
        self.plaintext_output_prompt.setGeometry(QtCore.QRect(10, 260, 401, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plaintext_output_prompt.setFont(font)
        self.plaintext_output_prompt.setStyleSheet("")
        self.plaintext_output_prompt.setObjectName("plaintext_output_prompt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 21))
        self.menubar.setObjectName("menubar")
        self.menuPage = QtWidgets.QMenu(self.menubar)
        self.menuPage.setObjectName("menuPage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInference = QtWidgets.QAction(MainWindow)
        self.actionInference.setObjectName("actionInference")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionPrompt = QtWidgets.QAction(MainWindow)
        self.actionPrompt.setObjectName("actionPrompt")
        self.actionSwitch_To_Big = QtWidgets.QAction(MainWindow)
        self.actionSwitch_To_Big.setObjectName("actionSwitch_To_Big")
        self.menuPage.addAction(self.actionSwitch_To_Big)
        self.menubar.addAction(self.menuPage.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ollama LLM"))
        self.button_process_text_prompt.setText(_translate("MainWindow", "Generate"))
        self.button_clear_chat.setText(_translate("MainWindow", "Clear Chat"))
        self.plaintext_output_prompt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuPage.setTitle(_translate("MainWindow", "Window"))
        self.actionInference.setText(_translate("MainWindow", "Text Inference"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionPrompt.setText(_translate("MainWindow", "Prompt"))
        self.actionSwitch_To_Big.setText(_translate("MainWindow", "Switch To Big"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
